In [2]:
import tensorflow as tf
import numpy as np

#2차원 배열 정의
mat1= [[1, 2, 3, 4],
       [5, 6, 7, 8]]

mat2= [[9, 10, 11, 12],
       [13, 14, 15, 16]]

mat3= [[17, 18, 19, 20],
       [21, 22, 23, 24]]

#텐서 변환 constant 이용
tensor1 = tf.constant([mat1, mat2, mat3])

print("rank : ", tf.rank(tensor1))
print("tensor1 : ", tensor1)

rank :  tf.Tensor(3, shape=(), dtype=int32)
tensor1 :  tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)

In [3]:
#텐서 변환 stack 이용
tensor2 = tf.stack([mat1, mat2, mat3])

print("rank : ", tf.rank(tensor2))
print("tensor 2 : ", tensor2)

rank :  tf.Tensor(3, shape=(), dtype=int32)
tensor 2 :  tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)

In [4]:
vec1 = [1, 2, 3, 4]
vec2 = [5, 6, 7, 8]
vec3 = [9, 10, 11, 12]
vec4 = [13, 14, 15, 16]
vec5 = [17, 18, 19, 20]
vec6 = [21, 22, 23 ,24]

arr = [[vec1, vec2],
       [vec3, vec4],
       [vec5, vec6]]

#텐서 변환
tensor3 = tf.constant(arr)

print("rank : ", tf.rank(tensor3))
print("tensor3 : ", tensor3)

rank :  tf.Tensor(3, shape=(), dtype=int32)
tensor3 :  tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)

In [6]:
#4차원 텐서 만들기
tensor4 = tf.stack([tensor1, tensor2])

print("rank : ", tf.rank(tensor4))
print("tensor4 : ", tensor4)

rank :  tf.Tensor(4, shape=(), dtype=int32)
tensor4 :  tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]]]


 [[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]]]], shape=(2, 3, 2, 4), dtype=int32)